name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo gem install mdl
          mdl -s .github/linter/readme_style.rb README.md
          mdl -s .github/linter/base_style.rb .github

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Build l1
        run: yarn workspace l1 run build
      - name: Install and format check in operator
        run: yarn workspace operator run format:check

  l2-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./l2
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: 0.41.0                  
      - run: scarb --version
      - run: scarb test

